version: '3.8'
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    container_name: go
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - .:/app
    networks:
      - default
  db:
    container_name: db
    build: 
     context: .
     dockerfile: ./db/Dockerfile
    tty: true
    ports:
     - 3306:3306
    environment:
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     MYSQL_DATABASE: ${MYSQL_DATABASE}
     MYSQL_USER:  ${MYSQL_USER}
     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
     - type: volume
       source: mysql_data
       target: /var/lib/mysql
    networks:
     - default


networks:
 default:
volumes:
 mysql_data:
